-- ============================================================================
-- OC · Contraloría Fase 1 — catálogo contable + empresa pagadora + urgencia
-- ============================================================================
-- Incorpora al ERP el flujo diseñado por el contralor (app oc-corporativo):
--  1. Catálogo de cuentas contables SAT (488 cuentas, derivadas de
--     CUENTAS_IAE160824L54.xlsx) para clasificar cada OC → cruce contable y
--     gasto por rubro.
--  2. ordenes_compra.empresa_pagadora_id: quién PAGA puede diferir de quién
--     solicita (operación inter-empresa del grupo). Backfill = empresa_id.
--  3. Urgencia de pago + fecha límite en días hábiles (SLA de tesorería).
--  4. tipo_compra (gasto/obra/material/activo/servicio/anticipo/otro) que
--     sugiere el rubro contable.
-- Idempotente (IF NOT EXISTS / ON CONFLICT) por la política de deriva remota.
-- ============================================================================

CREATE TABLE IF NOT EXISTS cuentas_contables (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  clave TEXT NOT NULL UNIQUE,
  descripcion TEXT NOT NULL,
  rubro TEXT NOT NULL,
  activo BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cuentas_contables_rubro
  ON cuentas_contables(rubro) WHERE activo = TRUE;

ALTER TABLE cuentas_contables ENABLE ROW LEVEL SECURITY;

-- Catálogo del grupo: lectura para cualquier usuario activo; gestión directivo.
DROP POLICY IF EXISTS cuentas_contables_select ON cuentas_contables;
CREATE POLICY cuentas_contables_select ON cuentas_contables
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM usuarios_empresas
    WHERE usuario_id = auth.uid() AND activo = TRUE
  ));

DROP POLICY IF EXISTS cuentas_contables_modify ON cuentas_contables;
CREATE POLICY cuentas_contables_modify ON cuentas_contables
  FOR ALL TO authenticated
  USING (usuario_es_ceo())
  WITH CHECK (usuario_es_ceo());

-- Columnas nuevas en ordenes_compra (aditivas).
ALTER TABLE ordenes_compra
  ADD COLUMN IF NOT EXISTS empresa_pagadora_id UUID REFERENCES empresas(id),
  ADD COLUMN IF NOT EXISTS cuenta_contable_id UUID REFERENCES cuentas_contables(id),
  ADD COLUMN IF NOT EXISTS tipo_compra TEXT
    CHECK (tipo_compra IS NULL OR tipo_compra IN
      ('gasto','obra','material','activo','servicio','anticipo','otro')),
  ADD COLUMN IF NOT EXISTS urgencia TEXT NOT NULL DEFAULT 'cero'
    CHECK (urgencia IN ('cero','bajo','medio','alto','critica')),
  ADD COLUMN IF NOT EXISTS limite_pago DATE;

-- Backfill: la pagadora es la solicitante donde no se haya distinguido.
UPDATE ordenes_compra SET empresa_pagadora_id = empresa_id
WHERE empresa_pagadora_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_oc_pagadora
  ON ordenes_compra(empresa_pagadora_id);
CREATE INDEX IF NOT EXISTS idx_oc_limite_pago
  ON ordenes_compra(limite_pago)
  WHERE limite_pago IS NOT NULL AND estado NOT IN ('pagada','cancelada');

-- ----------------------------------------------------------------------------
-- Seed del catálogo (488 cuentas). ON CONFLICT: re-aplicable.
-- ----------------------------------------------------------------------------
INSERT INTO cuentas_contables (clave, descripcion, rubro) VALUES
  ('115', 'Inventario', 'Inventarios'),
  ('115-01', 'Inventario', 'Inventarios'),
  ('115-02', 'Materia prima y materiales', 'Inventarios'),
  ('115-03', 'Producción en proceso', 'Inventarios'),
  ('115-04', 'Productos terminados', 'Inventarios'),
  ('115-05', 'Mercancías en tránsito', 'Inventarios'),
  ('115-06', 'Mercancías en poder de terceros', 'Inventarios'),
  ('115-07', 'Otros', 'Inventarios'),
  ('120', 'Anticipo a proveedores', 'Pagos Anticipados'),
  ('120-01', 'Anticipo a proveedores nacional', 'Pagos Anticipados'),
  ('120-02', 'Anticipo a proveedores extranjero', 'Pagos Anticipados'),
  ('120-03', 'Anticipo a proveedores nacional parte relacionada', 'Pagos Anticipados'),
  ('120-04', 'Anticipo a proveedores extranjero parte relacionada', 'Pagos Anticipados'),
  ('151', 'Terrenos', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('151-01', 'Terrenos', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('152', 'Edificios', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('152-01', 'Edificios', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('153', 'Maquinaria y equipo', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('153-01', 'Maquinaria y equipo', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('154', 'Automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('154-01', 'Automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('155', 'Mobiliario y equipo de oficina', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('155-01', 'Mobiliario y equipo de oficina', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('156', 'Equipo de cómputo', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('156-01', 'Equipo de cómputo', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('157', 'Equipo de comunicación', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('157-01', 'Equipo de comunicación', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('159', 'Obras en proceso de activos fijos', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('159-01', 'Obras en proceso de activos fijos', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('160', 'Otros activos fijos', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('160-01', 'Otros activos fijos', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('164', 'Troqueles, moldes, matrices y herramental', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('164-01', 'Troqueles, moldes, matrices y herramental', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('169', 'Otra maquinaria y equipo', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('169-01', 'Otra maquinaria y equipo', 'Inmuebles, Maquinaria Y Equipo Neto'),
  ('173', 'Gastos diferidos', 'Activos Intangibles'),
  ('173-01', 'Gastos diferidos', 'Activos Intangibles'),
  ('176', 'Activos intangibles', 'Activos Intangibles'),
  ('176-01', 'Activos intangibles', 'Activos Intangibles'),
  ('181', 'Gastos de instalación', 'Activos Intangibles'),
  ('181-01', 'Gastos de instalación', 'Activos Intangibles'),
  ('184', 'Depósitos en garantía', 'Activos Intangibles'),
  ('184-01', 'Depósitos de fianzas', 'Activos Intangibles'),
  ('184-02', 'Depósitos de arrendamiento de bienes inmuebles', 'Activos Intangibles'),
  ('184-03', 'Otros depósitos en garantía', 'Activos Intangibles'),
  ('501-01', 'Costo de venta', 'Costo De Ventas'),
  ('501-02', 'Costo de servicios (Mano de obra)', 'Costo De Ventas'),
  ('501-03', 'Materia prima directa utilizada para la producción', 'Costo De Ventas'),
  ('501-04', 'Materia prima consumida en el proceso productivo', 'Costo De Ventas'),
  ('501-05', 'Mano de obra directa consumida', 'Costo De Ventas'),
  ('501-06', 'Mano de obra directa', 'Costo De Ventas'),
  ('501-07', 'Cargos indirectos de producción', 'Costo De Ventas'),
  ('501-08', 'Otros conceptos de costo', 'Costo De Ventas'),
  ('502-01', 'Compras nacionales', 'Costo De Ventas'),
  ('502-02', 'Compras nacionales parte relacionada', 'Costo De Ventas'),
  ('502-03', 'Compras de Importación', 'Costo De Ventas'),
  ('502-04', 'Compras de Importación partes relacionadas', 'Costo De Ventas'),
  ('503-01', 'Devoluciones, descuentos o bonificaciones sobre compras', 'Costo De Ventas'),
  ('504-01', 'Gastos indirectos de fabricación', 'Costo De Ventas'),
  ('504-02', 'Gastos indirectos de fabricación de partes relacionadas nacionales', 'Costo De Ventas'),
  ('504-03', 'Gastos indirectos de fabricación de partes relacionadas extranjeras', 'Costo De Ventas'),
  ('504-04', 'Otras cuentas de costos incurridos', 'Costo De Ventas'),
  ('504-05', 'Otras cuentas de costos incurridos con partes relacionadas nacionales', 'Costo De Ventas'),
  ('504-06', 'Otras cuentas de costos incurridos con partes relacionadas extranjeras', 'Costo De Ventas'),
  ('504-07', 'Depreciación de edificios', 'Costo De Ventas'),
  ('504-08', 'Depreciación de maquinaria y equipo', 'Costo De Ventas'),
  ('504-09', 'Depreciación de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolque', 'Costo De Ventas'),
  ('504-10', 'Depreciación de mobiliario y equipo de oficina', 'Costo De Ventas'),
  ('504-11', 'Depreciación de equipo de cómputo', 'Costo De Ventas'),
  ('504-12', 'Depreciación de equipo de comunicación', 'Costo De Ventas'),
  ('504-13', 'Depreciación de activos biológicos, vegetales y semovientes', 'Costo De Ventas'),
  ('504-14', 'Depreciación de otros activos fijos', 'Costo De Ventas'),
  ('504-15', 'Depreciación de ferrocarriles', 'Costo De Ventas'),
  ('504-16', 'Depreciación de embarcaciones', 'Costo De Ventas'),
  ('504-17', 'Depreciación de aviones', 'Costo De Ventas'),
  ('504-18', 'Depreciación de troqueles, moldes, matrices y herramental', 'Costo De Ventas'),
  ('504-19', 'Depreciación de equipo de comunicaciones telefónicas', 'Costo De Ventas'),
  ('504-20', 'Depreciación de equipo de comunicación satelital', 'Costo De Ventas'),
  ('504-21', 'Depreciación de equipo de adaptaciones para personas con capacidades diferentes', 'Costo De Ventas'),
  ('504-22', 'Depreciación de maquinaria y equipo de generación de energía de fuentes renovables o de sistemas', 'Costo De Ventas'),
  ('504-23', 'Depreciación de adaptaciones y mejoras', 'Costo De Ventas'),
  ('504-24', 'Depreciación de otra maquinaria y equipo', 'Costo De Ventas'),
  ('504-25', 'Otras cuentas de costos', 'Costo De Ventas'),
  ('505-01', 'Costo por venta de activo fijo', 'Otros Gastos'),
  ('505-02', 'Costo por baja de activo fijo', 'Otros Gastos'),
  ('601-01', 'Sueldos y salarios', 'Gastos Generales'),
  ('601-02', 'Compensaciones', 'Gastos Generales'),
  ('601-03', 'Tiempos extras', 'Gastos Generales'),
  ('601-04', 'Premios de asistencia', 'Gastos Generales'),
  ('601-05', 'Premios de puntualidad', 'Gastos Generales'),
  ('601-06', 'Vacaciones', 'Gastos Generales'),
  ('601-07', 'Prima vacacional', 'Gastos Generales'),
  ('601-08', 'Prima dominical', 'Gastos Generales'),
  ('601-09', 'Días festivos', 'Gastos Generales'),
  ('601-10', 'Gratificaciones', 'Gastos Generales'),
  ('601-11', 'Primas de antigüedad', 'Gastos Generales'),
  ('601-12', 'Aguinaldo', 'Gastos Generales'),
  ('601-13', 'Indemnizaciones', 'Gastos Generales'),
  ('601-14', 'Destajo', 'Gastos Generales'),
  ('601-15', 'Despensa', 'Gastos Generales'),
  ('601-16', 'Transporte', 'Gastos Generales'),
  ('601-17', 'Servicio médico', 'Gastos Generales'),
  ('601-18', 'Ayuda en gastos funerarios', 'Gastos Generales'),
  ('601-19', 'Fondo de ahorro', 'Gastos Generales'),
  ('601-20', 'Cuotas sindicales', 'Gastos Generales'),
  ('601-21', 'PTU', 'Gastos Generales'),
  ('601-22', 'Estímulo al personal', 'Gastos Generales'),
  ('601-23', 'Previsión social', 'Gastos Generales'),
  ('601-24', 'Aportaciones para el plan de jubilación', 'Gastos Generales'),
  ('601-25', 'Otras prestaciones al personal', 'Gastos Generales'),
  ('601-26', 'Cuotas al IMSS', 'Gastos Generales'),
  ('601-27', 'Aportaciones al Infonavit', 'Gastos Generales'),
  ('601-28', 'Aportaciones al SAR', 'Gastos Generales'),
  ('601-29', 'Impuesto estatal sobre nóminas', 'Gastos Generales'),
  ('601-30', 'Otras aportaciones', 'Gastos Generales'),
  ('601-31', 'Asimilados a salarios', 'Gastos Generales'),
  ('601-32', 'Servicios administrativos', 'Gastos Generales'),
  ('601-33', 'Servicios administrativos partes relacionadas', 'Gastos Generales'),
  ('601-34', 'Honorarios a personas fisicas residentes nacionales', 'Gastos Generales'),
  ('601-35', 'Honorarios a personas fisicas residentes nacionales partes relacionadas', 'Gastos Generales'),
  ('601-36', 'Honorarios a personas fisicas residentes del extranjero', 'Gastos Generales'),
  ('601-37', 'Honorarios a personas fisicas residentes del extranjero partes relacionadas', 'Gastos Generales'),
  ('601-38', 'Honorarios a personas morales residentes nacionales', 'Gastos Generales'),
  ('601-39', 'Honorarios a personas morales residentes nacionales partes relacionadas', 'Gastos Generales'),
  ('601-40', 'Honorarios a personas morales residentes del extranjero', 'Gastos Generales'),
  ('601-41', 'Honorarios a personas morales residentes del extranjero partes relacionadas', 'Gastos Generales'),
  ('601-42', 'Honorarios aduanales personas fisicas', 'Gastos Generales'),
  ('601-43', 'Honorarios aduanales personas morales', 'Gastos Generales'),
  ('601-44', 'Honorarios al consejo de administración', 'Gastos Generales'),
  ('601-45', 'Arrendamiento a personas fisicas residentes nacionales', 'Gastos Generales'),
  ('601-46', 'Arrendamiento a personas morales residentes nacionales', 'Gastos Generales'),
  ('601-47', 'Arrendamiento a residentes del extranjero', 'Gastos Generales'),
  ('601-48', 'Combustibles y lubricantes', 'Gastos Generales'),
  ('601-49', 'Viaticos y gastos de viaje', 'Gastos Generales'),
  ('601-50', 'Teléfono, internet', 'Gastos Generales'),
  ('601-51', 'Agua', 'Gastos Generales'),
  ('601-52', 'Energía electrica', 'Gastos Generales'),
  ('601-53', 'Vigilancia y seguridad', 'Gastos Generales'),
  ('601-54', 'Limpieza', 'Gastos Generales'),
  ('601-55', 'Papelería y artículos de oficina', 'Gastos Generales'),
  ('601-56', 'Mantenimiento y conservación', 'Gastos Generales'),
  ('601-57', 'Seguros y fianzas', 'Gastos Generales'),
  ('601-58', 'Otros impuestos y derechos', 'Gastos Generales'),
  ('601-59', 'Recargos fiscales', 'Gastos Generales'),
  ('601-60', 'Cuotas y suscripciones', 'Gastos Generales'),
  ('601-61', 'Propaganda y publicidad', 'Gastos Generales'),
  ('601-62', 'Capacitación al personal', 'Gastos Generales'),
  ('601-63', 'Donativos y ayudas', 'Gastos Generales'),
  ('601-64', 'Asistencia técnica', 'Gastos Generales'),
  ('601-65', 'Regalías sujetas a otros porcentajes', 'Gastos Generales'),
  ('601-66', 'Regalías sujetas al 5%', 'Gastos Generales'),
  ('601-67', 'Regalías sujetas al 10%', 'Gastos Generales'),
  ('601-68', 'Regalías sujetas al 15%', 'Gastos Generales'),
  ('601-69', 'Regalías sujetas al 25%', 'Gastos Generales'),
  ('601-70', 'Regalías sujetas al 30%', 'Gastos Generales'),
  ('601-71', 'Regalías sin retención', 'Gastos Generales'),
  ('601-72', 'Fletes y acarreos', 'Gastos Generales'),
  ('601-73', 'Gastos de importación', 'Gastos Generales'),
  ('601-74', 'Comisiones sobre ventas', 'Gastos Generales'),
  ('601-75', 'Comisiones por tarjetas de crédito', 'Gastos Generales'),
  ('601-76', 'Patentes y marcas', 'Gastos Generales'),
  ('601-77', 'Uniformes', 'Gastos Generales'),
  ('601-78', 'Prediales', 'Gastos Generales'),
  ('601-79', 'Gastos generales de urbanización', 'Gastos Generales'),
  ('601-80', 'Gastos generales de construcción', 'Gastos Generales'),
  ('601-81', 'Fletes del extranjero', 'Gastos Generales'),
  ('601-82', 'Recolección de bienes del sector agropecuario y/o ganadero', 'Gastos Generales'),
  ('601-83', 'Gastos no deducibles (sin requisitos fiscales)', 'Gastos Generales'),
  ('601-84', 'Otros gastos generales', 'Gastos Generales'),
  ('601-85', 'Certificado de competencia', 'Gastos Generales'),
  ('601-86', 'Mantenimiento y conservacion   campus victoria', 'Gastos Generales'),
  ('601-87', 'Servicio de tramite por interconexion CFE', 'Gastos Generales'),
  ('601-88', 'Placas', 'Gastos Generales'),
  ('601-89', 'Renta de Maquinaria y Equipo', 'Gastos Generales'),
  ('601-90', 'Peaje', 'Gastos Generales'),
  ('601-91', 'Herramientas y equipos', 'Gastos Generales'),
  ('601-92', 'Servicios varios', 'Gastos Generales'),
  ('602-01', 'Sueldos y salarios', 'Gastos De Venta'),
  ('602-02', 'Compensaciones', 'Gastos De Venta'),
  ('602-03', 'Tiempos extras', 'Gastos De Venta'),
  ('602-04', 'Premios de asistencia', 'Gastos De Venta'),
  ('602-05', 'Premios de puntualidad', 'Gastos De Venta'),
  ('602-06', 'Vacaciones', 'Gastos De Venta'),
  ('602-07', 'Prima vacacional', 'Gastos De Venta'),
  ('602-08', 'Prima dominical', 'Gastos De Venta'),
  ('602-09', 'Días festivos', 'Gastos De Venta'),
  ('602-10', 'Gratificaciones', 'Gastos De Venta'),
  ('602-11', 'Primas de antigüedad', 'Gastos De Venta'),
  ('602-12', 'Aguinaldo', 'Gastos De Venta'),
  ('602-13', 'Indemnizaciones', 'Gastos De Venta'),
  ('602-14', 'Destajo', 'Gastos De Venta'),
  ('602-15', 'Despensa', 'Gastos De Venta'),
  ('602-16', 'Transporte', 'Gastos De Venta'),
  ('602-17', 'Servicio médico', 'Gastos De Venta'),
  ('602-18', 'Ayuda en gastos funerarios', 'Gastos De Venta'),
  ('602-19', 'Fondo de ahorro', 'Gastos De Venta'),
  ('602-20', 'Cuotas sindicales', 'Gastos De Venta'),
  ('602-21', 'PTU', 'Gastos De Venta'),
  ('602-22', 'Estímulo al personal', 'Gastos De Venta'),
  ('602-23', 'Previsión social', 'Gastos De Venta'),
  ('602-24', 'Aportaciones para el plan de jubilación', 'Gastos De Venta'),
  ('602-25', 'Otras prestaciones al personal', 'Gastos De Venta'),
  ('602-26', 'Cuotas al IMSS', 'Gastos De Venta'),
  ('602-27', 'Aportaciones al Infonavit', 'Gastos De Venta'),
  ('602-28', 'Aportaciones al SAR', 'Gastos De Venta'),
  ('602-29', 'Impuesto estatal sobre nóminas', 'Gastos De Venta'),
  ('602-30', 'Otras aportaciones', 'Gastos De Venta'),
  ('602-31', 'Asimilados a salarios', 'Gastos De Venta'),
  ('602-32', 'Servicios administrativos', 'Gastos De Venta'),
  ('602-33', 'Servicios administrativos partes relacionadas', 'Gastos De Venta'),
  ('602-34', 'Honorarios a personas fisicas residentes nacionales', 'Gastos De Venta'),
  ('602-35', 'Honorarios a personas fisicas residentes nacionales partes relacionadas', 'Gastos De Venta'),
  ('602-36', 'Honorarios a personas fisicas residentes del extranjero', 'Gastos De Venta'),
  ('602-37', 'Honorarios a personas fisicas residentes del extranjero partes relacionadas', 'Gastos De Venta'),
  ('602-38', 'Honorarios a personas morales residentes nacionales', 'Gastos De Venta'),
  ('602-39', 'Honorarios a personas morales residentes nacionales partes relacionadas', 'Gastos De Venta'),
  ('602-40', 'Honorarios a personas morales residentes del extranjero', 'Gastos De Venta'),
  ('602-41', 'Honorarios a personas morales residentes del extranjero partes relacionadas', 'Gastos De Venta'),
  ('602-42', 'Honorarios aduanales personas fisicas', 'Gastos De Venta'),
  ('602-43', 'Honorarios aduanales personas morales', 'Gastos De Venta'),
  ('602-44', 'Honorarios al consejo de administración', 'Gastos De Venta'),
  ('602-45', 'Arrendamiento a personas fisicas residentes nacionales', 'Gastos De Venta'),
  ('602-46', 'Arrendamiento a personas morales residentes nacionales', 'Gastos De Venta'),
  ('602-47', 'Arrendamiento a residentes del extranjero', 'Gastos De Venta'),
  ('602-48', 'Combustibles y lubricantes', 'Gastos De Venta'),
  ('602-49', 'Viaticos y gastos de viaje', 'Gastos De Venta'),
  ('602-50', 'Teléfono, internet', 'Gastos De Venta'),
  ('602-51', 'Agua', 'Gastos De Venta'),
  ('602-52', 'Energía electrica', 'Gastos De Venta'),
  ('602-53', 'Vigilancia y seguridad', 'Gastos De Venta'),
  ('602-54', 'Limpieza', 'Gastos De Venta'),
  ('602-55', 'Papelería y artículos de oficina', 'Gastos De Venta'),
  ('602-56', 'Mantenimiento y conservación', 'Gastos De Venta'),
  ('602-57', 'Seguros y fianzas', 'Gastos De Venta'),
  ('602-58', 'Otros impuestos y derechos', 'Gastos De Venta'),
  ('602-59', 'Recargos fiscales', 'Gastos De Venta'),
  ('602-60', 'Cuotas y suscripciones', 'Gastos De Venta'),
  ('602-61', 'Propaganda y publicidad', 'Gastos De Venta'),
  ('602-62', 'Capacitación al personal', 'Gastos De Venta'),
  ('602-63', 'Donativos y ayudas', 'Gastos De Venta'),
  ('602-64', 'Asistencia técnica', 'Gastos De Venta'),
  ('602-65', 'Regalías sujetas a otros porcentajes', 'Gastos De Venta'),
  ('602-66', 'Regalías sujetas al 5%', 'Gastos De Venta'),
  ('602-67', 'Regalías sujetas al 10%', 'Gastos De Venta'),
  ('602-68', 'Regalías sujetas al 15%', 'Gastos De Venta'),
  ('602-69', 'Regalías sujetas al 25%', 'Gastos De Venta'),
  ('602-70', 'Regalías sujetas al 30%', 'Gastos De Venta'),
  ('602-71', 'Regalías sin retención', 'Gastos De Venta'),
  ('602-72', 'Fletes y acarreos', 'Gastos De Venta'),
  ('602-73', 'Gastos de importación', 'Gastos De Venta'),
  ('602-74', 'Comisiones sobre ventas', 'Gastos De Venta'),
  ('602-75', 'Comisiones por tarjetas de crédito', 'Gastos De Venta'),
  ('602-76', 'Patentes y marcas', 'Gastos De Venta'),
  ('602-77', 'Uniformes', 'Gastos De Venta'),
  ('602-78', 'Prediales', 'Gastos De Venta'),
  ('602-79', 'Gastos de venta de urbanización', 'Gastos De Venta'),
  ('602-80', 'Gastos de venta de construcción', 'Gastos De Venta'),
  ('602-81', 'Fletes del extranjero', 'Gastos De Venta'),
  ('602-82', 'Recolección de bienes del sector agropecuario y/o ganadero', 'Gastos De Venta'),
  ('602-83', 'Gastos no deducibles (sin requisitos fiscales)', 'Gastos De Venta'),
  ('602-84', 'Otros gastos de venta', 'Gastos De Venta'),
  ('603-01', 'Sueldos y salarios', 'Gastos De Administracion'),
  ('603-02', 'Compensaciones', 'Gastos De Administracion'),
  ('603-03', 'Tiempos extras', 'Gastos De Administracion'),
  ('603-04', 'Premios de asistencia', 'Gastos De Administracion'),
  ('603-05', 'Premios de puntualidad', 'Gastos De Administracion'),
  ('603-06', 'Vacaciones', 'Gastos De Administracion'),
  ('603-07', 'Prima vacacional', 'Gastos De Administracion'),
  ('603-08', 'Prima dominical', 'Gastos De Administracion'),
  ('603-09', 'Días festivos', 'Gastos De Administracion'),
  ('603-10', 'Gratificaciones', 'Gastos De Administracion'),
  ('603-11', 'Primas de antigüedad', 'Gastos De Administracion'),
  ('603-12', 'Aguinaldo', 'Gastos De Administracion'),
  ('603-13', 'Indemnizaciones', 'Gastos De Administracion'),
  ('603-14', 'Destajo', 'Gastos De Administracion'),
  ('603-15', 'Despensa', 'Gastos De Administracion'),
  ('603-16', 'Transporte', 'Gastos De Administracion'),
  ('603-17', 'Servicio médico', 'Gastos De Administracion'),
  ('603-18', 'Ayuda en gastos funerarios', 'Gastos De Administracion'),
  ('603-19', 'Fondo de ahorro', 'Gastos De Administracion'),
  ('603-20', 'Cuotas sindicales', 'Gastos De Administracion'),
  ('603-21', 'PTU', 'Gastos De Administracion'),
  ('603-22', 'Estímulo al personal', 'Gastos De Administracion'),
  ('603-23', 'Previsión social', 'Gastos De Administracion'),
  ('603-24', 'Aportaciones para el plan de jubilación', 'Gastos De Administracion'),
  ('603-25', 'Otras prestaciones al personal', 'Gastos De Administracion'),
  ('603-26', 'Cuotas al IMSS', 'Gastos De Administracion'),
  ('603-27', 'Aportaciones al Infonavit', 'Gastos De Administracion'),
  ('603-28', 'Aportaciones al SAR', 'Gastos De Administracion'),
  ('603-29', 'Impuesto estatal sobre nóminas', 'Gastos De Administracion'),
  ('603-30', 'Otras aportaciones', 'Gastos De Administracion'),
  ('603-31', 'Asimilados a salarios', 'Gastos De Administracion'),
  ('603-32', 'Servicios administrativos', 'Gastos De Administracion'),
  ('603-33', 'Servicios administrativos partes relacionadas', 'Gastos De Administracion'),
  ('603-34', 'Honorarios a personas fisicas residentes nacionales', 'Gastos De Administracion'),
  ('603-35', 'Honorarios a personas fisicas residentes nacionales partes relacionadas', 'Gastos De Administracion'),
  ('603-36', 'Honorarios a personas fisicas residentes del extranjero', 'Gastos De Administracion'),
  ('603-37', 'Honorarios a personas fisicas residentes del extranjero partes relacionadas', 'Gastos De Administracion'),
  ('603-38', 'Honorarios a personas morales residentes nacionales', 'Gastos De Administracion'),
  ('603-39', 'Honorarios a personas morales residentes nacionales partes relacionadas', 'Gastos De Administracion'),
  ('603-40', 'Honorarios a personas morales residentes del extranjero', 'Gastos De Administracion'),
  ('603-41', 'Honorarios a personas morales residentes del extranjero partes relacionadas', 'Gastos De Administracion'),
  ('603-42', 'Honorarios aduanales personas fisicas', 'Gastos De Administracion'),
  ('603-43', 'Honorarios aduanales personas morales', 'Gastos De Administracion'),
  ('603-44', 'Honorarios al consejo de administración', 'Gastos De Administracion'),
  ('603-45', 'Arrendamiento a personas fisicas residentes nacionales', 'Gastos De Administracion'),
  ('603-46', 'Arrendamiento a personas morales residentes nacionales', 'Gastos De Administracion'),
  ('603-47', 'Arrendamiento a residentes del extranjero', 'Gastos De Administracion'),
  ('603-48', 'Combustibles y lubricantes', 'Gastos De Administracion'),
  ('603-49', 'Viaticos y gastos de viaje', 'Gastos De Administracion'),
  ('603-50', 'Teléfono, internet', 'Gastos De Administracion'),
  ('603-51', 'Agua', 'Gastos De Administracion'),
  ('603-52', 'Energía electrica', 'Gastos De Administracion'),
  ('603-53', 'Vigilancia y seguridad', 'Gastos De Administracion'),
  ('603-54', 'Limpieza', 'Gastos De Administracion'),
  ('603-55', 'Papelería y artículos de oficina', 'Gastos De Administracion'),
  ('603-56', 'Mantenimiento y conservación', 'Gastos De Administracion'),
  ('603-57', 'Seguros y fianzas', 'Gastos De Administracion'),
  ('603-58', 'Otros impuestos y derechos', 'Gastos De Administracion'),
  ('603-59', 'Recargos fiscales', 'Gastos De Administracion'),
  ('603-60', 'Cuotas y suscripciones', 'Gastos De Administracion'),
  ('603-61', 'Propaganda y publicidad', 'Gastos De Administracion'),
  ('603-62', 'Capacitación al personal', 'Gastos De Administracion'),
  ('603-63', 'Donativos y ayudas', 'Gastos De Administracion'),
  ('603-64', 'Asistencia técnica', 'Gastos De Administracion'),
  ('603-65', 'Regalías sujetas a otros porcentajes', 'Gastos De Administracion'),
  ('603-66', 'Regalías sujetas al 5%', 'Gastos De Administracion'),
  ('603-67', 'Regalías sujetas al 10%', 'Gastos De Administracion'),
  ('603-68', 'Regalías sujetas al 15%', 'Gastos De Administracion'),
  ('603-69', 'Regalías sujetas al 25%', 'Gastos De Administracion'),
  ('603-70', 'Regalías sujetas al 30%', 'Gastos De Administracion'),
  ('603-71', 'Regalías sin retención', 'Gastos De Administracion'),
  ('603-72', 'Fletes y acarreos', 'Gastos De Administracion'),
  ('603-73', 'Gastos de importación', 'Gastos De Administracion'),
  ('603-74', 'Patentes y marcas', 'Gastos De Administracion'),
  ('603-75', 'Uniformes', 'Gastos De Administracion'),
  ('603-76', 'Prediales', 'Gastos De Administracion'),
  ('603-77', 'Gastos de administración de urbanización', 'Gastos De Administracion'),
  ('603-78', 'Gastos de administración de construcción', 'Gastos De Administracion'),
  ('603-79', 'Fletes del extranjero', 'Gastos De Administracion'),
  ('603-80', 'Recolección de bienes del sector agropecuario y/o ganadero', 'Gastos De Administracion'),
  ('603-81', 'Gastos no deducibles (sin requisitos fiscales)', 'Gastos De Administracion'),
  ('603-82', 'Otros gastos de administración', 'Gastos De Administracion'),
  ('604-01', 'Sueldos y salarios', 'Costo De Ventas'),
  ('604-02', 'Compensaciones', 'Costo De Ventas'),
  ('604-03', 'Tiempos extras', 'Costo De Ventas'),
  ('604-04', 'Premios de asistencia', 'Costo De Ventas'),
  ('604-05', 'Premios de puntualidad', 'Costo De Ventas'),
  ('604-06', 'Vacaciones', 'Costo De Ventas'),
  ('604-07', 'Prima vacacional', 'Costo De Ventas'),
  ('604-08', 'Prima dominical', 'Costo De Ventas'),
  ('604-09', 'Días festivos', 'Costo De Ventas'),
  ('604-10', 'Gratificaciones', 'Costo De Ventas'),
  ('604-11', 'Primas de antigüedad', 'Costo De Ventas'),
  ('604-12', 'Aguinaldo', 'Costo De Ventas'),
  ('604-13', 'Indemnizaciones', 'Costo De Ventas'),
  ('604-14', 'Destajo', 'Costo De Ventas'),
  ('604-15', 'Despensa', 'Costo De Ventas'),
  ('604-16', 'Transporte', 'Costo De Ventas'),
  ('604-17', 'Servicio médico', 'Costo De Ventas'),
  ('604-18', 'Ayuda en gastos funerarios', 'Costo De Ventas'),
  ('604-19', 'Fondo de ahorro', 'Costo De Ventas'),
  ('604-20', 'Cuotas sindicales', 'Costo De Ventas'),
  ('604-21', 'PTU', 'Costo De Ventas'),
  ('604-22', 'Estímulo al personal', 'Costo De Ventas'),
  ('604-23', 'Previsión social', 'Costo De Ventas'),
  ('604-24', 'Aportaciones para el plan de jubilación', 'Costo De Ventas'),
  ('604-25', 'Otras prestaciones al personal', 'Costo De Ventas'),
  ('604-26', 'Cuotas al IMSS', 'Costo De Ventas'),
  ('604-27', 'Aportaciones al Infonavit', 'Costo De Ventas'),
  ('604-28', 'Aportaciones al SAR', 'Costo De Ventas'),
  ('604-29', 'Impuesto estatal sobre nóminas', 'Costo De Ventas'),
  ('604-30', 'Otras aportaciones', 'Costo De Ventas'),
  ('604-31', 'Asimilados a salarios', 'Costo De Ventas'),
  ('604-32', 'Servicios administrativos', 'Costo De Ventas'),
  ('604-33', 'Servicios administrativos partes relacionadas', 'Costo De Ventas'),
  ('604-34', 'Honorarios a personas fisicas residentes nacionales', 'Costo De Ventas'),
  ('604-35', 'Honorarios a personas fisicas residentes nacionales partes relacionadas', 'Costo De Ventas'),
  ('604-36', 'Honorarios a personas fisicas residentes del extranjero', 'Costo De Ventas'),
  ('604-37', 'Honorarios a personas fisicas residentes del extranjero partes relacionadas', 'Costo De Ventas'),
  ('604-38', 'Honorarios a personas morales residentes nacionales', 'Costo De Ventas'),
  ('604-39', 'Honorarios a personas morales residentes nacionales partes relacionadas', 'Costo De Ventas'),
  ('604-40', 'Honorarios a personas morales residentes del extranjero', 'Costo De Ventas'),
  ('604-41', 'Honorarios a personas morales residentes del extranjero partes relacionadas', 'Costo De Ventas'),
  ('604-42', 'Honorarios aduanales personas fisicas', 'Costo De Ventas'),
  ('604-43', 'Honorarios aduanales personas morales', 'Costo De Ventas'),
  ('604-44', 'Honorarios al consejo de administración', 'Costo De Ventas'),
  ('604-45', 'Arrendamiento a personas fisicas residentes nacionales', 'Costo De Ventas'),
  ('604-46', 'Arrendamiento a personas morales residentes nacionales', 'Costo De Ventas'),
  ('604-47', 'Arrendamiento a residentes del extranjero', 'Costo De Ventas'),
  ('604-48', 'Combustibles y lubricantes', 'Costo De Ventas'),
  ('604-49', 'Viaticos y gastos de viaje', 'Costo De Ventas'),
  ('604-50', 'Teléfono, internet', 'Costo De Ventas'),
  ('604-51', 'Agua', 'Costo De Ventas'),
  ('604-52', 'Energía electrica', 'Costo De Ventas'),
  ('604-53', 'Vigilancia y seguridad', 'Costo De Ventas'),
  ('604-54', 'Limpieza', 'Costo De Ventas'),
  ('604-55', 'Papelería y artículos de oficina', 'Costo De Ventas'),
  ('604-56', 'Mantenimiento y conservación', 'Costo De Ventas'),
  ('604-57', 'Seguros y fianzas', 'Costo De Ventas'),
  ('604-58', 'Otros impuestos y derechos', 'Costo De Ventas'),
  ('604-59', 'Recargos fiscales', 'Costo De Ventas'),
  ('604-60', 'Cuotas y suscripciones', 'Costo De Ventas'),
  ('604-61', 'Propaganda y publicidad', 'Costo De Ventas'),
  ('604-62', 'Capacitación al personal', 'Costo De Ventas'),
  ('604-63', 'Donativos y ayudas', 'Costo De Ventas'),
  ('604-64', 'Asistencia técnica', 'Costo De Ventas'),
  ('604-65', 'Regalías sujetas a otros porcentajes', 'Costo De Ventas'),
  ('604-66', 'Regalías sujetas al 5%', 'Costo De Ventas'),
  ('604-67', 'Regalías sujetas al 10%', 'Costo De Ventas'),
  ('604-68', 'Regalías sujetas al 15%', 'Costo De Ventas'),
  ('604-69', 'Regalías sujetas al 25%', 'Costo De Ventas'),
  ('604-70', 'Regalías sujetas al 30%', 'Costo De Ventas'),
  ('604-71', 'Regalías sin retención', 'Costo De Ventas'),
  ('604-72', 'Fletes y acarreos', 'Costo De Ventas'),
  ('604-73', 'Gastos de importación', 'Costo De Ventas'),
  ('604-74', 'Patentes y marcas', 'Costo De Ventas'),
  ('604-75', 'Uniformes', 'Costo De Ventas'),
  ('604-76', 'Prediales', 'Costo De Ventas'),
  ('604-77', 'Gastos de fabricación de urbanización', 'Costo De Ventas'),
  ('604-78', 'Gastos de fabricación de construcción', 'Costo De Ventas'),
  ('604-79', 'Fletes del extranjero', 'Costo De Ventas'),
  ('604-80', 'Recolección de bienes del sector agropecuario y/o ganadero', 'Costo De Ventas'),
  ('604-81', 'Gastos no deducibles (sin requisitos fiscales)', 'Costo De Ventas'),
  ('604-82', 'Otros gastos de fabricación', 'Costo De Ventas'),
  ('605-01', 'Mano de obra', 'Costo De Ventas'),
  ('605-02', 'Sueldos y Salarios', 'Costo De Ventas'),
  ('605-03', 'Compensaciones', 'Costo De Ventas'),
  ('605-04', 'Tiempos extras', 'Costo De Ventas'),
  ('605-05', 'Premios de asistencia', 'Costo De Ventas'),
  ('605-06', 'Premios de puntualidad', 'Costo De Ventas'),
  ('605-07', 'Vacaciones', 'Costo De Ventas'),
  ('605-08', 'Prima vacacional', 'Costo De Ventas'),
  ('605-09', 'Prima dominical', 'Costo De Ventas'),
  ('605-10', 'Días festivos', 'Costo De Ventas'),
  ('605-11', 'Gratificaciones', 'Costo De Ventas'),
  ('605-12', 'Primas de antigüedad', 'Costo De Ventas'),
  ('605-13', 'Aguinaldo', 'Costo De Ventas'),
  ('605-14', 'Indemnizaciones', 'Costo De Ventas'),
  ('605-15', 'Destajo', 'Costo De Ventas'),
  ('605-16', 'Despensa', 'Costo De Ventas'),
  ('605-17', 'Transporte', 'Costo De Ventas'),
  ('605-18', 'Servicio médico', 'Costo De Ventas'),
  ('605-19', 'Ayuda en gastos funerarios', 'Costo De Ventas'),
  ('605-20', 'Fondo de ahorro', 'Costo De Ventas'),
  ('605-21', 'Cuotas sindicales', 'Costo De Ventas'),
  ('605-22', 'PTU', 'Costo De Ventas'),
  ('605-23', 'Estímulo al personal', 'Costo De Ventas'),
  ('605-24', 'Previsión social', 'Costo De Ventas'),
  ('605-25', 'Aportaciones para el plan de jubilación', 'Costo De Ventas'),
  ('605-26', 'Otras prestaciones al personal', 'Costo De Ventas'),
  ('605-27', 'Asimilados a salarios', 'Costo De Ventas'),
  ('605-28', 'Cuotas al IMSS', 'Costo De Ventas'),
  ('605-29', 'Aportaciones al Infonavit', 'Costo De Ventas'),
  ('605-30', 'Aportaciones al SAR', 'Costo De Ventas'),
  ('605-31', 'Otros costos de mano de obra directa', 'Costo De Ventas'),
  ('701-01', 'Pérdida cambiaria', 'Resultado Integral De Financiamiento'),
  ('701-02', 'Pérdida cambiaria nacional parte relacionada', 'Resultado Integral De Financiamiento'),
  ('701-03', 'Pérdida cambiaria extranjero parte relacionada', 'Resultado Integral De Financiamiento'),
  ('701-04', 'Intereses a cargo bancario nacional', 'Resultado Integral De Financiamiento'),
  ('701-05', 'Intereses a cargo bancario extranjero', 'Resultado Integral De Financiamiento'),
  ('701-06', 'Intereses a cargo de personas físicas nacional', 'Resultado Integral De Financiamiento'),
  ('701-07', 'Intereses a cargo de personas físicas extranjero', 'Resultado Integral De Financiamiento'),
  ('701-08', 'Intereses a cargo de personas morales nacional', 'Resultado Integral De Financiamiento'),
  ('701-09', 'Intereses a cargo de personas morales extranjero', 'Resultado Integral De Financiamiento'),
  ('701-10', 'Comisiones bancarias', 'Resultado Integral De Financiamiento'),
  ('701-11', 'Otros gastos financieros', 'Resultado Integral De Financiamiento'),
  ('703-01', 'Pérdida en venta de terrenos', 'Otros Gastos'),
  ('703-02', 'Pérdida en venta de edificios', 'Otros Gastos'),
  ('703-03', 'Pérdida en venta de maquinaria y equipo', 'Otros Gastos'),
  ('703-04', 'Pérdida en venta de automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remo', 'Otros Gastos'),
  ('703-05', 'Pérdida en venta de mobiliario y equipo de oficina', 'Otros Gastos'),
  ('703-06', 'Pérdida en venta de equipo de cómputo', 'Otros Gastos'),
  ('703-07', 'Pérdida en venta de equipo de comunicación', 'Otros Gastos'),
  ('703-08', 'Pérdida en venta de activos biológicos, vegetales y semovientes', 'Otros Gastos'),
  ('703-09', 'Pérdida en venta de otros activos fijos', 'Otros Gastos'),
  ('703-10', 'Pérdida en venta de ferrocarriles', 'Otros Gastos'),
  ('703-11', 'Pérdida en venta de embarcaciones', 'Otros Gastos'),
  ('703-12', 'Pérdida en venta de aviones', 'Otros Gastos'),
  ('703-13', 'Pérdida en venta de troqueles, moldes, matrices y herramental', 'Otros Gastos'),
  ('703-14', 'Pérdida en venta de equipo de comunicaciones telefónicas', 'Otros Gastos'),
  ('703-15', 'Pérdida en venta de equipo de comunicación satelital', 'Otros Gastos'),
  ('703-16', 'Pérdida en venta de equipo de adaptaciones para personas con capacidades diferentes', 'Otros Gastos'),
  ('703-17', 'Pérdida en venta de maquinaria y equipo de generación de energía de fuentes renovables o de siste', 'Otros Gastos'),
  ('703-18', 'Pérdida en venta de otra maquinaria y equipo', 'Otros Gastos'),
  ('703-19', 'Pérdida por enajenación de acciones', 'Otros Gastos'),
  ('703-20', 'Pérdida por enajenación de partes sociales', 'Otros Gastos'),
  ('703-21', 'Otros gastos', 'Otros Gastos')
ON CONFLICT (clave) DO NOTHING;
